"""Add Column scores table ai

Revision ID: a8a267b39609
Revises: bbd0673cdb17
Create Date: 2024-03-23 15:37:14.431912+09:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a8a267b39609'
down_revision = 'bbd0673cdb17'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scores', sa.Column('ai', sa.String(length=50), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scores', 'ai')
    # ### end Alembic commands ###
