version: "3.9"

volumes:
  node_modules:
  postgres_data:

services:
  frontend:
    build:
      context: ./frontend/
      dockerfile: Dockerfile
    container_name: react_fastapi_frontend_container
    tty: true
    volumes:
      - .:/app
      # - node_modules:/app/frontend/node_modules
    ports:
      - 5173:5173
    command: yarn dev

  backend:
    build:
      context: ./backend/
      dockerfile: Dockerfile
    container_name: react_fastapi_backend_container
    ports:
      - 8080:8080
    tty: true
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: postgres-db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - 5432:5432
